### ISSUE TITLE
收藏了

### ISSUE THREAD

**Issue by songlongkuan** [micahh28/RemindDrinking#1]
建议编译一个成品贴上来 hhhhh....
晚上我回家下个vs studio 编译一番

**Comment by Chadwuo** [comment]
谢谢！女票用了快几个月了，反应效果很好，喝水明显多了，皮肤光滑了，腿也长了，感觉更加年轻了呢。关于您提起的成品，【RemindDrinking/RemDrinkSetup/ReleaseV5.02.zip】，该文件解压后即可在Windows平台上正常使用。如需更改提醒的时间、全屏图片或文字内容可能需要重新编译程序。
