### ISSUE TITLE
请问怎么修改提醒时间和提醒文字呢？本人是java开发，没用过vs没用过c，请简单并详细说一下大概原理，感谢

### ISSUE THREAD

**Issue by MaidongAndYida** [micahh28/RemindDrinking#2]

**Comment by Chadwuo** [comment]
因为一开始没有想过过多的设置。本着拿起就用的原则。提醒喝水的时间和文字，都是写在代码中。具体在【RemindDrinking/SystemTipsScheduler.cs】文件中注册有八条定时任务，分别在八个不同的时间段触发。在【RemindDrinking/TipsForm.cs】中有个简单的判断是什么时间段的任务，从而显示对应的提示文字和随机的图片。

**Comment by MaidongAndYida** [comment]
谢谢，我会仔细研究一下的。

**Comment by MaidongAndYida** [comment]
额，你好请问怎么把master的代码打包成exe可执行文件呢？

**Comment by Chadwuo** [comment]
该程序使用vs开发，download项目后，经vs重新编译后，即可生成新的可执行exe文件。另，我已经为没有vs的朋友生成好了可执行的安装包文件，位置：【RemindDrinking/RemDrinkSetup/ReleaseV5.02.zip】。

**Comment by MaidongAndYida** [comment]
我电脑不知为什么vs装不上，不知您能否帮我打一个包呢，谢谢了，我就修改一下其中的文字和图片就好，我改好后会将整个文件夹发给您，行？

**Comment by MaidongAndYida** [comment]
我是win7的系统，安装2010，2012，2013，都不能运行您的这个2017vs的编译出来的文件，请问可以帮忙修改一下文字和图片并重新发给我一个打包的安装包可执行文件吗？

**Comment by Chadwuo** [comment]
你留下邮箱，我晚上把程序改为可以修改图片及文字，编译好exe文件后发给你。

**Comment by MaidongAndYida** [comment]
棒棒哒  么么哒   13020851322@163.com   还是github的开发er有爱心，开心

**Comment by MaidongAndYida** [comment]
不用改成可以配置的了，我回家下载了一个vs2019，可以生成可以改，谢谢楼主的关心，thanks

**Comment by Chadwuo** [comment]
实在不好意思。作为一个优秀的开发者，是一定会拖更，这辈子都不会按时该项目的。开玩笑，不过你已经能打开就好，可能我的vs是2017  用的.net framework 4.5  导致你就得vs打不开。我近期会更新这个项目，加上设置时间文字图片等功能。如果你以后有需要，可以重新down新的代码。另，我同样会给你邮箱发邮件。

**Comment by MaidongAndYida** [comment]
没事没事，你能二次开发这个产品，我已经很开心了。
我想问一个问题，image里的图片只能是21个吗？怎么增加更多呢？

**Comment by MaidongAndYida** [comment]
你好，为什么我自己放上去的jpg图片显示不出来？

**Comment by MaidongAndYida** [comment]
昨天终于修改成可以显示自己的图片了，但是我不会打成msi安装包，我的2019vs安装project installer之后，还是无法在解决方案右键出添加新项目的操作。请问这是为什么呢？

**Comment by Chadwuo** [comment]
是的，旧版本 图片是放进了资源文件中，然后【TipsForm.cs】代码中从 资源文件中的图片随机拿出，我只做了20个。新的版本已经改变了这个方式，在程序文件夹中新增了【image】文件夹，可以放入自由更改照片。关于你的msi安装包问题，建议需要google一下vs打包安装程序方法，以获得更加详细的解决方案。

**Comment by MaidongAndYida** [comment]
额，不知可否您帮我打一个msi安装包呢？我将解决方案发给您，哥哥

**Comment by Chadwuo** [comment]
可以，我的QQ：1067051515
