### ISSUE TITLE
请问可以fork一个这个软件去独立开发吗

### ISSUE THREAD

**Issue by Helloat123** [micahh28/RemindDrinking#3]
我在fork完修改完之后发现你的软件没有添加协议，在查阅github相关文件后我得知未添加协议的程序照理来讲是一切权利归作者并且不能随便修改发布。我保证我的程序没有商业用途，请问我可以fork一个这个软件去独立开发吗？或者你可以加个gpl之类的协议？谢谢！如果不允许，我会尽快把我在github上的相关repository删除。

**Comment by Helloat123** [comment]
(从未接触过c#的弱鸡边研究边学)如果允许的话真是谢谢大佬支持

**Comment by Chadwuo** [comment]
当然可以，你完全可以修改发布。欢迎随时交流学习。
